services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: hypersphere_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: face_attendance
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hypersphere_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@postgres:5432/face_attendance
      - RECOGNITION_MODEL_PATH=/app/models/w600k_r50.onnx
      - ANTISPOOF_MODEL_PATH=/app/models/2.7_80x80_MiniFASNetV2.pth
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
